version: "3.9"
services:
    mqtt:
      image: eclipse-mosquitto
      container_name: mqtt
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./config:/mosquitto/config
        - data:/mosquitto/data
        - logs:/mosquitto/log
      networks:
        - mqtt-net
volumes:
  data:
  logs:

networks:
  mqtt-net:
    driver: bridge
